---
name: Publish to GH pages

on:
  push:
    branches:
      - master

  workflow_dispatch:
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pre-commit/action@v3.0.0

  build_and_deploy:
    needs: pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - run: npm run build
      - run: npm run deploy
